
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 130
#define YY_END_OF_BUFFER 131
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[514] =
    {   0,
        0,    0,  131,  129,  119,  118,  118,   16,  129,   35,
       33,  129,    1,    2,   31,   29,    8,   30,    9,   32,
      121,  121,   19,    7,   14,   13,   15,   18,   11,  128,
      128,    5,    6,   34,  117,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,    3,   50,    4,   17,  118,
       24,    0,  125,   46,   25,   43,    0,   41,   27,   39,
       28,   40,   20,    0,  122,    0,  120,   42,  122,  121,
        0,    0,  122,    0,  121,    0,    0,    0,    0,  121,
        0,   12,   36,   23,   51,   21,   22,   37,  128,  128,

       45,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,   69,  128,  128,  128,  128,  128,  128,  128,  128,
       62,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  112,  128,  128,  128,  128,  128,  128,  128,
       44,   26,  125,    0,  124,   10,  122,  122,    0,    0,
        0,    0,  120,  122,    0,  121,    0,  121,    0,    0,
      121,    0,  122,    0,  121,  121,    0,  121,    0,  121,
      121,    0,  121,    0,   47,   48,   38,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,

      128,  128,  128,  128,  128,  128,  128,   67,  128,  128,
      128,   79,  128,  128,  128,   52,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,   53,  128,
      111,  128,  128,  128,  128,  128,    0,    0,  122,    0,
        0,  122,    0,  120,  122,    0,    0,  122,  121,    0,
      121,  121,    0,  122,  122,    0,    0,    0,  121,  121,
        0,    0,  121,    0,  121,    0,    0,    0,  121,    0,
      121,    0,  121,    0,   49,  128,  128,  128,  128,  128,
       76,   65,  128,   81,  128,  128,  128,  128,  128,   63,

      110,  128,  128,  128,  128,  128,  117,  128,  128,  128,
      128,   80,  128,  128,    0,  126,   93,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,   71,  128,  128,  123,   94,  109,  128,
      128,   96,  128,    0,  122,    0,  122,    0,  122,    0,
      121,    0,  122,    0,    0,    0,  121,    0,    0,  122,
      121,    0,  121,    0,    0,    0,  121,    0,  121,    0,
      128,  128,  128,  128,   60,   54,   77,  128,  128,  128,
      128,  128,  101,   83,  128,  128,  128,  128,  128,  128,
        0,   92,  128,  128,  128,  128,  128,  128,  128,  128,

      128,  128,   78,  128,  128,   72,  128,  128,   57,  128,
      128,   68,  113,  127,  122,    0,  122,    0,    0,    0,
      122,  122,    0,    0,    0,   82,  128,   74,  128,  128,
      128,   84,  128,  128,  128,  128,   87,  128,  128,   89,
      116,    0,  128,  117,  128,  128,  128,  100,  115,  128,
       59,  102,   88,  128,   64,  128,   58,  128,  128,  122,
        0,  128,   75,  128,   66,   91,   85,   56,  128,  128,
      128,    0,   86,  108,   99,  128,  128,  128,  128,  128,
      128,  128,  128,   73,   61,  128,  128,  128,    0,  128,
       95,   90,  106,  128,  128,  128,  105,  128,  128,  114,

        0,   98,  128,  104,  128,  107,   70,  103,  128,   97,
      128,   55,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   29,   31,   32,   31,
       33,   33,   33,   33,   33,   34,   33,   33,   33,   35,
       33,   33,   36,   33,   33,   33,   33,   37,   33,   33,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   33,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[72] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    5,    5,
        5,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    6,    7,    8,    6,    6,    1,    9,    1,
        1,    8,    5,    5,    5,    5,    5,    5,    6,    6,
        6,    6,    7,    6,    6,    6,    8,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[532] =
    {   0,
        0,    0, 1026, 1027, 1027, 1027, 1022,  999, 1017,  997,
       64,    0, 1027, 1027,  996,   60, 1027,   61,   59,   71,
       81,  131,  998, 1027,   66,  994,   56, 1027, 1027,    0,
      957, 1027, 1027,  992,    0,   49,   39,   64,   47,   51,
       79,  960,   83,  959,  958,   97,  956,   96,  965,  110,
       86,  951,   65,  116,  959, 1027,   85, 1027, 1027, 1027,
     1027, 1003, 1002, 1027, 1027, 1027,  998, 1027, 1027, 1027,
     1027, 1027, 1027,  990,  162,  993,    0, 1027,  167,  200,
      238,  150, 1027,  182, 1027,  988,  207,  171,  987,  218,
      245, 1027,  977, 1027, 1027, 1027, 1027,  166,    0,  942,

     1027,  940,  939,  942,  950,  935,  145,  952,  951,  938,
      944,  929,  930,  927,  150,  935,  932,  930,  926,  923,
        0,  926,  162,  927,  935,  919,  915,  923,  924,  929,
      930,  915,   68,  929,  103,  929,  915,  153,  913,  918,
      913,   82,    0,  209,  920,  907,  182,  914,  903,  916,
     1027, 1027, 1027,  956, 1027, 1027,  258, 1027,  278,  289,
      949,  158,    0,  293,  302,  225,    0, 1027,  308,  324,
      314,  333,  339,    0,  348,  353,  356,  344,    0,  368,
      373,  388,  393,  398, 1027, 1027,  935,  908,  897,  910,
      903,  912,  907,  906,  907,  892,  890,  169,  906,  904,

      900,  892,  889,  897,  883,  899,  898,    0,  884,  239,
      878,  891,  888,  874,  884,    0,  919,  880,  877,  879,
      876,  865,  211,  874,  868,  861,  857,  862,  855,  849,
      855,  858,  840,  851,  813,  797,  797,  797,    0,  779,
        0,  792,  794,  782,  784,  780,  826,  825,  413,  408,
      418,  433,  238, 1027,  451,  447,  428,  482,    0,  466,
      472, 1027,  319,  491, 1027,  498,  226,  205,  507, 1027,
      532,  520,  438,  538,  547,  381,  246,  216,  551,  553,
        0,  578,  593,  597, 1027,  774,  768,  765,  776,  769,
        0,    0,  766,    0,  750,  743,  752,  740,  743,    0,

        0,  735,  738,  745,  737,  728,    0,  741,  727,  742,
      719,    0,  722,  711,  711,    0,  701,  715,  706,  713,
      699,  693,  691,  663,  657,  648,  658,  636,  645,  647,
      632,  641,  634,    0,  619,  617,    0,    0,    0,  615,
      610,    0,  610,  649,  603,  608,  612,  643,  647,  652,
      656,  502,  681,  661,  259,  526,  653,    0,  695,  699,
        0,  713,  706,  552,  669,  686,  719,    0,    0,  718,
      604,  609,  587,  604,    0,    0,    0,  591,  589,  594,
      579,  592,  584,    0,  582,  564,  564,  561,  560,  558,
      556,    0,  553,  540,  531,  546,  544,  539,  536,  520,

      523,  530,    0,  530,  513,    0,  522,  504,  488,  495,
      492,    0,    0, 1027,  731,  745,  749,  763,  311,    0,
      780, 1027,  788,  312,    0,    0,  493,    0,  480,  472,
      471,    0,  471,  469,  461,  479,    0,  470,  464,    0,
        0,  462,  457,  436,  448,  433,  445,    0,    0,  441,
        0,    0,    0,  430,    0,  421,    0,  318,  423,  794,
      799,  413,    0,  426,    0,    0,    0,    0,  408,  415,
      398,  389,    0,    0,    0,  394,  364,  362,  363,  349,
      341,  338,  341,    0,    0,  319,  299,  302,  289,  288,
        0,    0,    0,  279,  258,  255,    0,  242,  234,    0,

      195,    0,  157,    0,  170,    0,    0, 1027,  109,    0,
       80,    0, 1027,  842,  850,  854,  862,  871,  877,  879,
      884,   79,  890,   69,  895,  899,  904,  908,  913,  917,
      921
    } ;

static const flex_int16_t yy_def[532] =
    {   0,
      513,    1,  513,  513,  513,  513,  513,  513,  514,  513,
      513,  515,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  516,
      516,  513,  513,  513,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  513,  513,  513,  513,  513,
      513,  514,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  517,  518,  513,  513,  513,
      513,  513,  513,  513,  513,  519,  513,  513,  520,   22,
      513,  513,  513,  513,  513,  513,  513,  513,  516,  516,

      513,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      513,  513,  513,  521,  513,  513,  513,  513,  513,  513,
      517,  517,  518,  513,  513,   80,   81,  513,  513,  513,
      513,  513,  513,  522,  523,   80,  513,  513,  524,  525,
       22,  513,   22,  513,  513,  513,  513,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,

      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  521,  521,  513,  513,
      513,  513,  517,  513,  513,  513,  513,  513,  166,  513,
      513,  513,  513,  513,  513,  513,  526,  522,  527,  513,
      513,  527,  166,  513,  513,  513,  528,  524,  529,  529,
      181,  513,  181,  513,  513,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,

      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  513,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  521,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  530,  530,  272,  272,  513,  513,
      273,  513,  513,  513,  531,  531,  280,  280,  283,  513,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      513,  516,  516,  516,  516,  516,  516,  516,  516,  516,

      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  513,  513,  513,  513,  513,  356,  356,
      513,  513,  513,  366,  366,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  513,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  513,
      513,  516,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  513,  516,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  513,  516,
      516,  516,  516,  516,  516,  516,  516,  516,  516,  516,

      513,  516,  516,  516,  516,  516,  516,  513,  516,  516,
      516,  516,    0,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513
    } ;

static const flex_int16_t yy_nxt[1099] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   30,
       30,   30,   30,   30,   30,   31,   30,   32,    4,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   30,
       43,   30,   44,   45,   46,   47,   48,   30,   49,   50,
       51,   52,   53,   54,   30,   55,   30,   56,   57,   58,
       59,   65,   69,  277,   74,   71,   75,   75,   75,   75,
       97,   98,   76,  267,   70,   72,   73,   77,   66,   93,
       94,   95,  102,  111,  104,   78,   79,  105,   80,   80,

       80,   81,  112,  113,  106,  114,  107,  146,  103,  151,
       82,   83,   84,  108,   85,  115,  109,   86,  222,  110,
      147,  116,   87,  223,   88,  512,   83,   84,   83,  117,
      121,  118,  235,   85,  119,  142,  122,  123,  131,  126,
      236,  143,  132,  127,  144,   89,   79,  225,   90,   90,
       90,   90,  128,  152,  133,  511,  136,  134,  129,  137,
      226,   83,   84,  227,   85,  148,  149,  171,  171,  253,
      138,  139,   91,  140,  254,  141,   83,   84,   83,  157,
      157,  157,  157,   85,  164,  164,  164,  164,  178,  178,
      186,  187,  158,  159,  172,  230,  172,   83,  165,  173,

      173,  173,  173,  160,  194,  195,  203,  158,  159,  158,
      204,  231,   83,  165,   83,   79,  510,  166,  166,  166,
      167,  211,  212,  509,  176,  176,  176,  167,  296,  297,
       83,   84,  242,  168,  243,  181,  181,  181,  181,  271,
      508,  169,  259,  259,  259,   83,   84,   83,  177,  253,
      271,  237,  168,   79,  254,  167,  167,  167,  167,  182,
      271,  271,  183,  183,  183,  183,  260,  356,   83,   84,
      238,  321,  271,  322,  239,  249,  249,  249,  249,  170,
      271,  507,  271,   83,   84,   83,  184,  366,  158,  159,
      251,  308,  251,  271,  309,  252,  252,  252,  252,  250,

      420,  506,  271,  158,  159,  158,  249,  249,  249,  249,
      255,  255,  255,  255,  257,  271,  257,  505,  504,  258,
      258,  258,  258,   83,  165,  259,  259,  259,  167,  503,
      250,  261,  261,  502,  256,  501,  351,  351,   83,  165,
       83,  167,  167,  167,  167,  271,  271,  262,  500,  260,
      173,  173,  173,  173,  499,  263,  264,  264,  264,  264,
      352,  275,  275,  268,  481,  170,  262,  271,  271,  265,
      273,  273,  273,  176,  176,  176,  167,  262,  482,  498,
      266,  270,  271,  278,  265,  276,  265,  497,  496,  272,
      281,  281,  281,  281,  274,  495,  262,  177,  363,  363,

      270,  270,  271,  494,  271,  281,  281,  281,  281,  280,
      283,  283,  283,  283,  282,  183,  183,  183,  183,  493,
      270,  492,  364,  491,  271,  249,  249,  249,  249,  282,
      249,  249,  249,  249,  284,  252,  252,  252,  252,  184,
      490,  489,  488,  158,  159,  258,  258,  258,  258,  250,
      345,  345,  345,  345,  250,  361,  361,  361,  158,  159,
      158,  487,  486,  158,  347,  347,  347,  347,  347,  347,
      347,  347,  485,  484,  346,  483,  480,  479,  158,  362,
      158,   83,  165,  259,  259,  259,  167,  478,  348,  351,
      351,  477,  348,  476,  475,  474,   83,  165,   83,  349,

      349,  349,  349,  473,  472,  262,  471,  260,  353,  353,
      353,  353,   83,  352,  470,  353,  353,  353,  353,  351,
      351,  265,  268,  350,  262,  469,  468,   83,  467,   83,
      466,  465,  354,  464,  463,  513,  265,  462,  265,  354,
      270,  271,  459,  352,  359,  458,  359,  457,  358,  360,
      360,  360,  360,  513,  513,  361,  361,  361,  167,  270,
      513,  358,  456,  271,  363,  363,  278,  420,  513,  363,
      363,  455,  513,  454,  453,  452,  513,  451,  450,  362,
      262,  449,  513,  448,  270,  271,  513,  513,  364,  447,
      446,  445,  368,  364,  368,  281,  281,  281,  281,  262,

      444,  443,  442,  270,  441,  513,  440,  271,  439,  513,
      369,  369,  369,  369,  369,  369,  369,  369,  438,  282,
      415,  415,  415,  415,  437,  415,  415,  415,  415,  347,
      347,  347,  347,  158,  370,  436,  435,  434,  370,  433,
      432,  431,   83,  165,  416,  430,  429,  428,  158,  416,
      158,  427,  426,  348,  414,  413,  412,   83,  165,   83,
      347,  347,  347,  347,  417,  417,  417,  417,  268,  417,
      417,  417,  417,  351,  351,  411,  410,   83,  353,  353,
      353,  353,  409,  408,  348,  407,  270,  271,  418,  262,
      406,  405,   83,  418,   83,  404,  403,  352,  353,  353,

      353,  353,  354,  271,  402,  270,  401,  400,  262,  271,
      425,  265,  360,  360,  360,  360,  421,  421,  421,  421,
      513,  399,  354,  363,  363,  271,  265,  425,  265,  422,
      361,  361,  361,  167,  278,  369,  369,  369,  369,  262,
      423,  398,  513,  397,  422,  396,  422,  364,  415,  415,
      415,  415,  270,  271,  362,  395,  394,  393,  262,  370,
      392,  158,  415,  415,  415,  415,  417,  417,  417,  417,
      391,  270,  416,  390,  389,  271,  158,  388,  158,   83,
      417,  417,  417,  417,  387,  386,  416,  385,  384,  383,
      418,  337,  382,  381,   83,  380,   83,  460,  460,  460,

      460,  379,  378,  307,  418,  460,  460,  460,  460,  377,
      422,  460,  460,  460,  460,  376,  460,  460,  460,  460,
      375,  461,  374,  373,  422,  422,  372,  422,  371,  461,
      344,  248,  343,  342,  341,  461,  340,  339,  338,  422,
      461,  422,   62,  337,   62,   62,   62,   62,   62,   62,
       67,  336,  335,   67,   67,   67,   67,   67,   99,   99,
       99,   99,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  163,  334,  163,  163,  163,  163,  163,  163,  163,
      175,  175,  180,  180,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  269,  269,  333,  269,  269,  279,  279,

      332,  279,  279,  355,  331,  330,  355,  357,  357,  329,
      357,  357,  365,  328,  327,  365,  367,  367,  326,  367,
      367,  419,  325,  324,  419,  424,  323,  320,  424,  319,
      318,  317,  316,  315,  314,  313,  312,  311,  310,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  298,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      162,  248,  246,  245,  244,  241,  240,  234,  233,  232,
      229,  228,  224,  221,  220,  219,  218,  217,  216,  215,
      214,  213,  210,  209,  208,  207,  206,  205,  202,  201,
      200,  199,  198,  197,  196,  193,  192,  191,  190,  189,

      188,  185,  179,  174,  162,  156,  155,  154,  153,  150,
      145,  135,  130,  125,  124,  120,  101,  100,   96,   92,
       68,   64,   63,   61,   60,  513,    3,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513

    } ;

static const flex_int16_t yy_chk[1099] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   11,   16,  524,   19,   18,   19,   19,   19,   19,
       27,   27,   20,  522,   16,   18,   18,   20,   11,   25,
       25,   25,   36,   39,   37,   20,   21,   37,   21,   21,

       21,   21,   39,   40,   37,   40,   38,   53,   36,   57,
       21,   21,   21,   38,   21,   40,   38,   21,  133,   38,
       53,   41,   21,  133,   21,  511,   21,   21,   21,   41,
       43,   41,  142,   21,   41,   51,   43,   43,   48,   46,
      142,   51,   48,   46,   51,   21,   22,  135,   22,   22,
       22,   22,   46,   57,   48,  509,   50,   48,   46,   50,
      135,   22,   22,  135,   22,   54,   54,   82,   82,  162,
       50,   50,   22,   50,  162,   50,   22,   22,   22,   75,
       75,   75,   75,   22,   79,   79,   79,   79,   88,   88,
       98,   98,   75,   75,   84,  138,   84,   79,   79,   84,

       84,   84,   84,   75,  107,  107,  115,   75,   75,   75,
      115,  138,   79,   79,   79,   80,  505,   80,   80,   80,
       80,  123,  123,  503,   87,   87,   87,   87,  198,  198,
       80,   80,  147,   80,  147,   90,   90,   90,   90,  268,
      501,   80,  166,  166,  166,   80,   80,   80,   87,  253,
      278,  144,   80,   81,  253,   81,   81,   81,   81,   90,
      267,  268,   91,   91,   91,   91,  166,  267,   81,   81,
      144,  223,  278,  223,  144,  157,  157,  157,  157,   81,
      277,  499,  267,   81,   81,   81,   91,  277,  157,  157,
      159,  210,  159,  355,  210,  159,  159,  159,  159,  157,

      355,  498,  277,  157,  157,  157,  160,  160,  160,  160,
      164,  164,  164,  164,  165,  355,  165,  496,  495,  165,
      165,  165,  165,  164,  164,  169,  169,  169,  169,  494,
      160,  171,  171,  490,  164,  489,  263,  263,  164,  164,
      164,  170,  170,  170,  170,  419,  424,  171,  488,  169,
      172,  172,  172,  172,  487,  171,  173,  173,  173,  173,
      263,  178,  178,  175,  458,  170,  171,  419,  424,  173,
      176,  176,  176,  177,  177,  177,  177,  178,  458,  486,
      173,  175,  175,  180,  173,  178,  173,  483,  482,  175,
      181,  181,  181,  181,  176,  481,  178,  177,  276,  276,

      175,  180,  180,  480,  175,  182,  182,  182,  182,  180,
      183,  183,  183,  183,  181,  184,  184,  184,  184,  479,
      180,  478,  276,  477,  180,  250,  250,  250,  250,  182,
      249,  249,  249,  249,  183,  251,  251,  251,  251,  184,
      476,  472,  471,  249,  249,  257,  257,  257,  257,  250,
      252,  252,  252,  252,  249,  273,  273,  273,  249,  249,
      249,  470,  469,  252,  256,  256,  256,  256,  255,  255,
      255,  255,  464,  462,  252,  459,  456,  454,  252,  273,
      252,  255,  255,  260,  260,  260,  260,  450,  256,  261,
      261,  447,  255,  446,  445,  444,  255,  255,  255,  258,

      258,  258,  258,  443,  442,  261,  439,  260,  264,  264,
      264,  264,  258,  261,  438,  266,  266,  266,  266,  352,
      352,  264,  269,  258,  261,  436,  435,  258,  434,  258,
      433,  431,  264,  430,  429,  272,  264,  427,  264,  266,
      269,  269,  411,  352,  271,  410,  271,  409,  269,  271,
      271,  271,  271,  272,  272,  274,  274,  274,  274,  269,
      356,  272,  408,  269,  275,  275,  279,  356,  280,  364,
      364,  407,  272,  405,  404,  402,  272,  401,  400,  274,
      275,  399,  356,  398,  279,  279,  280,  280,  275,  397,
      396,  395,  279,  364,  280,  282,  282,  282,  282,  275,

      394,  393,  391,  279,  390,  280,  389,  279,  388,  280,
      283,  283,  283,  283,  284,  284,  284,  284,  387,  282,
      345,  345,  345,  345,  386,  346,  346,  346,  346,  347,
      347,  347,  347,  345,  283,  385,  383,  382,  284,  381,
      380,  379,  347,  347,  345,  378,  374,  373,  345,  346,
      345,  372,  371,  347,  344,  343,  341,  347,  347,  347,
      348,  348,  348,  348,  349,  349,  349,  349,  357,  350,
      350,  350,  350,  351,  351,  340,  336,  349,  354,  354,
      354,  354,  335,  333,  348,  332,  357,  357,  349,  351,
      331,  330,  349,  350,  349,  329,  328,  351,  353,  353,

      353,  353,  354,  365,  327,  357,  326,  325,  351,  357,
      365,  353,  359,  359,  359,  359,  360,  360,  360,  360,
      366,  324,  353,  363,  363,  365,  353,  366,  353,  360,
      362,  362,  362,  362,  367,  370,  370,  370,  370,  363,
      360,  323,  366,  322,  360,  321,  360,  363,  415,  415,
      415,  415,  367,  367,  362,  320,  319,  318,  363,  370,
      317,  415,  416,  416,  416,  416,  417,  417,  417,  417,
      315,  367,  415,  314,  313,  367,  415,  311,  415,  417,
      418,  418,  418,  418,  310,  309,  416,  308,  306,  305,
      417,  304,  303,  302,  417,  299,  417,  421,  421,  421,

      421,  298,  297,  296,  418,  423,  423,  423,  423,  295,
      421,  460,  460,  460,  460,  293,  461,  461,  461,  461,
      290,  421,  289,  288,  460,  421,  287,  421,  286,  423,
      248,  247,  246,  245,  244,  460,  243,  242,  240,  460,
      461,  460,  514,  238,  514,  514,  514,  514,  514,  514,
      515,  237,  236,  515,  515,  515,  515,  515,  516,  516,
      516,  516,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  518,  235,  518,  518,  518,  518,  518,  518,  518,
      519,  519,  520,  520,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  523,  523,  234,  523,  523,  525,  525,

      233,  525,  525,  526,  232,  231,  526,  527,  527,  230,
      527,  527,  528,  229,  228,  528,  529,  529,  227,  529,
      529,  530,  226,  225,  530,  531,  224,  222,  531,  221,
      220,  219,  218,  217,  215,  214,  213,  212,  211,  209,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      161,  154,  150,  149,  148,  146,  145,  141,  140,  139,
      137,  136,  134,  132,  131,  130,  129,  128,  127,  126,
      125,  124,  122,  120,  119,  118,  117,  116,  114,  113,
      112,  111,  110,  109,  108,  106,  105,  104,  103,  102,

      100,   93,   89,   86,   76,   74,   67,   63,   62,   55,
       52,   49,   47,   45,   44,   42,   34,   31,   26,   23,
       15,   10,    9,    8,    7,    3,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  513

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[131] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 
    1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 4 "lexer.l"
#include <bits/stdc++.h>
using namespace std;
#include "parser.tab.h"
extern YYSTYPE yylval;
extern int line;
int yylex();
#line 897 "lex.yy.c"
#line 898 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 82 "lexer.l"



#line 1119 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 514 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1027 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 85 "lexer.l"
{yylval.tit = yytext; line=yylineno; return OPEN_BRACKETST;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 86 "lexer.l"
{yylval.tit = yytext; line=yylineno; return CLOSE_BRACKETST;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 87 "lexer.l"
{yylval.tit = yytext; line=yylineno; return OPEN_CURLYT;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 88 "lexer.l"
{yylval.tit = yytext; line=yylineno; return CLOSE_CURLYT;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 89 "lexer.l"
{yylval.tit = yytext; line=yylineno; return OPEN_SQT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 90 "lexer.l"
{yylval.tit = yytext; line=yylineno; return CLOSE_SQT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 91 "lexer.l"
{yylval.tit = yytext; line=yylineno; return SEMICOLT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 92 "lexer.l"
{yylval.tit = yytext; line=yylineno; return COMMAT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DOTT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 94 "lexer.l"
{yylval.tit = yytext; line=yylineno; return TDOTT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 95 "lexer.l"
{yylval.tit = yytext; line=yylineno; return ATRT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 96 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DCOLT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 100 "lexer.l"
{yylval.tit = yytext; line=yylineno; return EQUALT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 101 "lexer.l"
{yylval.tit = yytext; line=yylineno; return LESST;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 102 "lexer.l"
{yylval.tit = yytext; line=yylineno; return GREATERT;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 103 "lexer.l"
{yylval.tit = yytext; line=yylineno; return EXCLAMATORYT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 104 "lexer.l"
{yylval.tit = yytext; line=yylineno; return TILDAT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 105 "lexer.l"
{yylval.tit = yytext; line=yylineno; return QUET;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 106 "lexer.l"
{yylval.tit = yytext; line=yylineno; return COLONT;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 107 "lexer.l"
{yylval.tit = yytext; line=yylineno; return IMPLIEST;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 108 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DEQUALT;}                                
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 109 "lexer.l"
{yylval.tit = yytext; line=yylineno; return GET;}                                
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 110 "lexer.l"
{yylval.tit = yytext; line=yylineno; return LET;}                                
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 111 "lexer.l"
{yylval.tit = yytext; line=yylineno; return NEQUALT;}                                
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 112 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DANDT;}                                
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 113 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DORT;}                                
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 114 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DPLUST;}                                
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 115 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DMINUST;}                                
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 116 "lexer.l"
{yylval.tit = yytext; line=yylineno; return PLUST;}                          
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 117 "lexer.l"
{yylval.tit = yytext; line=yylineno; return MINUST;}                          
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 118 "lexer.l"
{yylval.tit = yytext; line=yylineno; return MULT;}                          
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 119 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DIVIDET;}                          
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 120 "lexer.l"
{yylval.tit = yytext; line=yylineno; return ANDT;}                          
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 121 "lexer.l"
{yylval.tit = yytext; line=yylineno; return HATT;}                          
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 122 "lexer.l"
{yylval.tit = yytext; line=yylineno; return MODULOT;}                          
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 123 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DLESST;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 124 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DGREATERT;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 125 "lexer.l"
{yylval.tit = yytext; line=yylineno; return TGREATERT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 126 "lexer.l"
{yylval.tit = yytext; line=yylineno; return PLUS_EQUALT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 127 "lexer.l"
{yylval.tit = yytext; line=yylineno; return MINUS_EQUALT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 128 "lexer.l"
{yylval.tit = yytext; line=yylineno; return MUL_EQUALT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 129 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DIVIDE_EQUALT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 130 "lexer.l"
{yylval.tit = yytext; line=yylineno; return AND_EQUALT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 131 "lexer.l"
{yylval.tit = yytext; line=yylineno; return OR_EQUALT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 132 "lexer.l"
{yylval.tit = yytext; line=yylineno; return HAT_EQUALT;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 133 "lexer.l"
{yylval.tit = yytext; line=yylineno; return MODULO_EQUALT;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 134 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DLESS_EQUALT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 135 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DGREATER_EQUALT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 136 "lexer.l"
{yylval.tit = yytext; line=yylineno; return TGREATER_EQUALT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 137 "lexer.l"
{yylval.tit = yytext; line=yylineno; return ORT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 138 "lexer.l"
{yylval.tit = yytext; line=yylineno; return LGT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 140 "lexer.l"
{yylval.tit = yytext; line=yylineno; return NEWT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 141 "lexer.l"
{yylval.tit = yytext; line=yylineno; return TRYT;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 142 "lexer.l"
{yylval.tit = yytext; line=yylineno; return CATCHT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 143 "lexer.l"
{yylval.tit = yytext; line=yylineno; return SYNCHRONIZEDT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 144 "lexer.l"
{yylval.tit = yytext; line=yylineno; return FINALLYT;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 145 "lexer.l"
{yylval.tit = yytext; line=yylineno; return THROWT;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 146 "lexer.l"
{yylval.tit = yytext; line=yylineno; return THROWST;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 147 "lexer.l"
{yylval.tit = yytext; line=yylineno; return RETURNT;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 148 "lexer.l"
{yylval.tit = yytext; line=yylineno; return BREAKT;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 149 "lexer.l"
{yylval.tit = yytext; line=yylineno; return CONTINUET;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 150 "lexer.l"
{yylval.tit = yytext; line=yylineno; return IFT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 151 "lexer.l"
{yylval.tit = yytext; line=yylineno; return ELSET;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 152 "lexer.l"
{yylval.tit = yytext; line=yylineno; return SWITCHT;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 153 "lexer.l"
{yylval.tit = yytext; line=yylineno; return CASET;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 154 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DEFAULTT;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 155 "lexer.l"
{yylval.tit = yytext; line=yylineno; return FORT;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 156 "lexer.l"
{yylval.tit = yytext; line=yylineno; return WHILET;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 157 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DOOT;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 158 "lexer.l"
{yylval.tit = yytext; line=yylineno; return INSTANCEOFT;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 159 "lexer.l"
{yylval.tit = yytext; line=yylineno; return THIST;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 160 "lexer.l"
{yylval.tit = yytext; line=yylineno; return SUPERT;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 161 "lexer.l"
{yylval.tit = yytext; line=yylineno; return ABSTRACTT;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 162 "lexer.l"
{yylval.tit = yytext; line=yylineno; return ASSERTT;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 163 "lexer.l"
{yylval.tit = yytext; line=yylineno; return BOOLEANT;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 164 "lexer.l"
{yylval.tit = yytext; line=yylineno; return BYTET;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 165 "lexer.l"
{yylval.tit = yytext; line=yylineno; return CLASST;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 166 "lexer.l"
{yylval.tit = yytext; line=yylineno; return SHORTT;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 167 "lexer.l"
{yylval.tit = yytext; line=yylineno; return INTT;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 168 "lexer.l"
{yylval.tit = yytext; line=yylineno; return LONGT;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 169 "lexer.l"
{yylval.tit = yytext; line=yylineno; return CHART;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 170 "lexer.l"
{yylval.tit = yytext; line=yylineno; return STRINGT;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 171 "lexer.l"
{yylval.tit = yytext; line=yylineno; return FLOATT;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 172 "lexer.l"
{yylval.tit = yytext; line=yylineno; return DOUBLET;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 173 "lexer.l"
{yylval.tit = yytext; line=yylineno; return EXTENDST;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 174 "lexer.l"
{yylval.tit = yytext; line=yylineno; return PACKAGET;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 175 "lexer.l"
{yylval.tit = yytext; line=yylineno; return IMPORTT;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 176 "lexer.l"
{yylval.tit = yytext; line=yylineno; return STATICT;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 177 "lexer.l"
{yylval.tit = yytext; line=yylineno; return MODULET;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 178 "lexer.l"
{yylval.tit = yytext; line=yylineno; return REQUIREST;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 179 "lexer.l"
{yylval.tit = yytext; line=yylineno; return EXPORTST;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 180 "lexer.l"
{yylval.tit = yytext; line=yylineno; return OPENST;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 181 "lexer.l"
{yylval.tit = yytext; line=yylineno; return OPENT;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 182 "lexer.l"
{yylval.tit = yytext; line=yylineno; return USEST;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 183 "lexer.l"
{yylval.tit = yytext; line=yylineno; return PROVIDEST;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 184 "lexer.l"
{yylval.tit = yytext; line=yylineno; return WITHT;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 185 "lexer.l"
{yylval.tit = yytext; line=yylineno; return TRANSITIVET;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 186 "lexer.l"
{yylval.tit = yytext; line=yylineno; return PROTECTEDT;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 187 "lexer.l"
{yylval.tit = yytext; line=yylineno; return PRIVATET;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 188 "lexer.l"
{yylval.tit = yytext; line=yylineno; return PUBLICT;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 189 "lexer.l"
{yylval.tit = yytext; line=yylineno; return FINALT;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 190 "lexer.l"
{yylval.tit = yytext; line=yylineno; return SEALEDT;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 191 "lexer.l"
{yylval.tit = yytext; line=yylineno; return NONSEALEDT;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 192 "lexer.l"
{yylval.tit = yytext; line=yylineno; return TRANSIENTT;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 193 "lexer.l"
{yylval.tit = yytext; line=yylineno; return VOLATILET;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 194 "lexer.l"
{yylval.tit = yytext; line=yylineno; return STRICTFPT;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 195 "lexer.l"
{yylval.tit = yytext; line=yylineno; return IMPLEMENTST;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 196 "lexer.l"
{yylval.tit = yytext; line=yylineno; return PERMITST;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 197 "lexer.l"
{yylval.tit = yytext; line=yylineno; return VOIDT;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 198 "lexer.l"
{yylval.tit = yytext; line=yylineno; return ENUMT;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 199 "lexer.l"
{yylval.tit = yytext; line=yylineno; return VART;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 200 "lexer.l"
{yylval.tit = yytext; line=yylineno; return TOT;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 201 "lexer.l"
{yylval.tit = yytext; line=yylineno; return YIELDT;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 202 "lexer.l"
{yylval.tit = yytext; line=yylineno; return INTERFACET;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 203 "lexer.l"
{yylval.tit = yytext; line=yylineno; return RECORDT;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 204 "lexer.l"
{yylval.tit = yytext; line=yylineno; return NATIVET;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 205 "lexer.l"
{yylval.tit = yytext; line=yylineno; return keywordT;}
	YY_BREAK
case 118:
/* rule 118 can match eol */
YY_RULE_SETUP
#line 206 "lexer.l"
/*skip*/
	YY_BREAK
case 119:
/* rule 119 can match eol */
YY_RULE_SETUP
#line 207 "lexer.l"
/* Skip WhiteSpace */
	YY_BREAK
case 120:
/* rule 120 can match eol */
YY_RULE_SETUP
#line 208 "lexer.l"
/* Skip Comment */
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 209 "lexer.l"
{yylval.tit = yytext; line=yylineno; return IntegerLiteralT;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 210 "lexer.l"
{yylval.tit = yytext; line=yylineno; return FloatingPointLiteralT;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 211 "lexer.l"
{yylval.tit = yytext; line=yylineno; return BooleanLiteralT;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 212 "lexer.l"
{yylval.tit = yytext; line=yylineno; return CharacterLiteralT;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 213 "lexer.l"
{yylval.tit = yytext; line=yylineno; return StringLiteralT;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 214 "lexer.l"
{yylval.tit = yytext; line=yylineno; return NullLiteralT;}
	YY_BREAK
case 127:
/* rule 127 can match eol */
YY_RULE_SETUP
#line 215 "lexer.l"
{yylval.tit = yytext; line=yylineno; return TextBlockT;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 216 "lexer.l"
{yylval.tit = yytext; line=yylineno; return identifierT; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 218 "lexer.l"
{  }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 220 "lexer.l"
ECHO;
	YY_BREAK
#line 1840 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 514 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 514 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 513);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 220 "lexer.l"


int yywrap (void) {return 1;}
